# Fly.io config for frontend (static via Nginx)
app = "diet-ai-frontend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "requests"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
